/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\viruser.v-desktop\\Desktop\\learning\\blog3\\docs\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-683b7183",
    path: "/%E7%AC%94%E8%AE%B0/react.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-683b7183").then(next)
    },
  },
  {
    path: "/笔记/react.html",
    redirect: "/%E7%AC%94%E8%AE%B0/react.html"
  },
  {
    path: "/笔记/react.html",
    redirect: "/%E7%AC%94%E8%AE%B0/react.html"
  },
  {
    name: "v-49fd8c75",
    path: "/%E7%AC%94%E8%AE%B0/vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-49fd8c75").then(next)
    },
  },
  {
    path: "/笔记/vue.html",
    redirect: "/%E7%AC%94%E8%AE%B0/vue.html"
  },
  {
    path: "/笔记/vue.html",
    redirect: "/%E7%AC%94%E8%AE%B0/vue.html"
  },
  {
    name: "v-674e7503",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-674e7503").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-91614d68",
    path: "/%E5%85%B3%E4%BA%8E%E6%88%91/country.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-91614d68").then(next)
    },
  },
  {
    path: "/关于我/country.html",
    redirect: "/%E5%85%B3%E4%BA%8E%E6%88%91/country.html"
  },
  {
    path: "/关于我/country.html",
    redirect: "/%E5%85%B3%E4%BA%8E%E6%88%91/country.html"
  },
  {
    name: "v-732c4808",
    path: "/%E5%85%B3%E4%BA%8E%E6%88%91/family.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-732c4808").then(next)
    },
  },
  {
    path: "/关于我/family.html",
    redirect: "/%E5%85%B3%E4%BA%8E%E6%88%91/family.html"
  },
  {
    path: "/关于我/family.html",
    redirect: "/%E5%85%B3%E4%BA%8E%E6%88%91/family.html"
  },
  {
    name: "v-68c91ddc",
    path: "/%E5%85%B3%E4%BA%8E%E6%88%91/play.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-68c91ddc").then(next)
    },
  },
  {
    path: "/关于我/play.html",
    redirect: "/%E5%85%B3%E4%BA%8E%E6%88%91/play.html"
  },
  {
    path: "/关于我/play.html",
    redirect: "/%E5%85%B3%E4%BA%8E%E6%88%91/play.html"
  },
  {
    name: "v-233cf9c6",
    path: "/%E5%85%B3%E4%BA%8E%E6%88%91/sports.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-233cf9c6").then(next)
    },
  },
  {
    path: "/关于我/sports.html",
    redirect: "/%E5%85%B3%E4%BA%8E%E6%88%91/sports.html"
  },
  {
    path: "/关于我/sports.html",
    redirect: "/%E5%85%B3%E4%BA%8E%E6%88%91/sports.html"
  },
  {
    name: "v-2ff711fb",
    path: "/%E7%AC%94%E8%AE%B0/css.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2ff711fb").then(next)
    },
  },
  {
    path: "/笔记/css.html",
    redirect: "/%E7%AC%94%E8%AE%B0/css.html"
  },
  {
    path: "/笔记/css.html",
    redirect: "/%E7%AC%94%E8%AE%B0/css.html"
  },
  {
    name: "v-739c915b",
    path: "/%E7%AC%94%E8%AE%B0/html.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-739c915b").then(next)
    },
  },
  {
    path: "/笔记/html.html",
    redirect: "/%E7%AC%94%E8%AE%B0/html.html"
  },
  {
    path: "/笔记/html.html",
    redirect: "/%E7%AC%94%E8%AE%B0/html.html"
  },
  {
    name: "v-b184a194",
    path: "/%E9%9D%A2%E7%BB%8F/css.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b184a194").then(next)
    },
  },
  {
    path: "/面经/css.html",
    redirect: "/%E9%9D%A2%E7%BB%8F/css.html"
  },
  {
    path: "/面经/css.html",
    redirect: "/%E9%9D%A2%E7%BB%8F/css.html"
  },
  {
    name: "v-1641dd82",
    path: "/%E9%A1%B9%E7%9B%AE/java.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1641dd82").then(next)
    },
  },
  {
    path: "/项目/java.html",
    redirect: "/%E9%A1%B9%E7%9B%AE/java.html"
  },
  {
    path: "/项目/java.html",
    redirect: "/%E9%A1%B9%E7%9B%AE/java.html"
  },
  {
    name: "v-49aac57e",
    path: "/%E9%9D%A2%E7%BB%8F/html.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-49aac57e").then(next)
    },
  },
  {
    path: "/面经/html.html",
    redirect: "/%E9%9D%A2%E7%BB%8F/html.html"
  },
  {
    path: "/面经/html.html",
    redirect: "/%E9%9D%A2%E7%BB%8F/html.html"
  },
  {
    name: "v-b482187c",
    path: "/%E9%A1%B9%E7%9B%AE/vue2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b482187c").then(next)
    },
  },
  {
    path: "/项目/vue2.html",
    redirect: "/%E9%A1%B9%E7%9B%AE/vue2.html"
  },
  {
    path: "/项目/vue2.html",
    redirect: "/%E9%A1%B9%E7%9B%AE/vue2.html"
  },
  {
    name: "v-355c7c4a",
    path: "/%E9%A1%B9%E7%9B%AE/react.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-355c7c4a").then(next)
    },
  },
  {
    path: "/项目/react.html",
    redirect: "/%E9%A1%B9%E7%9B%AE/react.html"
  },
  {
    path: "/项目/react.html",
    redirect: "/%E9%A1%B9%E7%9B%AE/react.html"
  },
  {
    name: "v-254b8862",
    path: "/%E9%A1%B9%E7%9B%AE/vue3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-254b8862").then(next)
    },
  },
  {
    path: "/项目/vue3.html",
    redirect: "/%E9%A1%B9%E7%9B%AE/vue3.html"
  },
  {
    path: "/项目/vue3.html",
    redirect: "/%E9%A1%B9%E7%9B%AE/vue3.html"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]