/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\pargrammer\\blog\\docs\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-54523be1",
    path: "/%E5%85%B3%E4%BA%8E%E6%88%91/sports.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-54523be1").then(next)
    },
  },
  {
    path: "/关于我/sports.html",
    redirect: "/%E5%85%B3%E4%BA%8E%E6%88%91/sports.html"
  },
  {
    path: "/关于我/sports.html",
    redirect: "/%E5%85%B3%E4%BA%8E%E6%88%91/sports.html"
  },
  {
    name: "v-76f1a577",
    path: "/%E5%85%B3%E4%BA%8E%E6%88%91/play.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-76f1a577").then(next)
    },
  },
  {
    path: "/关于我/play.html",
    redirect: "/%E5%85%B3%E4%BA%8E%E6%88%91/play.html"
  },
  {
    path: "/关于我/play.html",
    redirect: "/%E5%85%B3%E4%BA%8E%E6%88%91/play.html"
  },
  {
    name: "v-0fc6feb2",
    path: "/%E5%85%B3%E4%BA%8E%E6%88%91/country.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0fc6feb2").then(next)
    },
  },
  {
    path: "/关于我/country.html",
    redirect: "/%E5%85%B3%E4%BA%8E%E6%88%91/country.html"
  },
  {
    path: "/关于我/country.html",
    redirect: "/%E5%85%B3%E4%BA%8E%E6%88%91/country.html"
  },
  {
    name: "v-004c6c70",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-004c6c70").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-11cef15e",
    path: "/%E9%9D%A2%E7%BB%8F/css.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-11cef15e").then(next)
    },
  },
  {
    path: "/面经/css.html",
    redirect: "/%E9%9D%A2%E7%BB%8F/css.html"
  },
  {
    path: "/面经/css.html",
    redirect: "/%E9%9D%A2%E7%BB%8F/css.html"
  },
  {
    name: "v-3821ceb6",
    path: "/%E7%AC%94%E8%AE%B0/html.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3821ceb6").then(next)
    },
  },
  {
    path: "/笔记/html.html",
    redirect: "/%E7%AC%94%E8%AE%B0/html.html"
  },
  {
    path: "/笔记/html.html",
    redirect: "/%E7%AC%94%E8%AE%B0/html.html"
  },
  {
    name: "v-0e3002d9",
    path: "/%E9%9D%A2%E7%BB%8F/html.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0e3002d9").then(next)
    },
  },
  {
    path: "/面经/html.html",
    redirect: "/%E9%9D%A2%E7%BB%8F/html.html"
  },
  {
    path: "/面经/html.html",
    redirect: "/%E9%9D%A2%E7%BB%8F/html.html"
  },
  {
    name: "v-7fd1ea16",
    path: "/%E7%AC%94%E8%AE%B0/css.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7fd1ea16").then(next)
    },
  },
  {
    path: "/笔记/css.html",
    redirect: "/%E7%AC%94%E8%AE%B0/css.html"
  },
  {
    path: "/笔记/css.html",
    redirect: "/%E7%AC%94%E8%AE%B0/css.html"
  },
  {
    name: "v-4a71ca46",
    path: "/%E9%A1%B9%E7%9B%AE/java.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4a71ca46").then(next)
    },
  },
  {
    path: "/项目/java.html",
    redirect: "/%E9%A1%B9%E7%9B%AE/java.html"
  },
  {
    path: "/项目/java.html",
    redirect: "/%E9%A1%B9%E7%9B%AE/java.html"
  },
  {
    name: "v-24f06236",
    path: "/%E9%A1%B9%E7%9B%AE/react.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-24f06236").then(next)
    },
  },
  {
    path: "/项目/react.html",
    redirect: "/%E9%A1%B9%E7%9B%AE/react.html"
  },
  {
    path: "/项目/react.html",
    redirect: "/%E9%A1%B9%E7%9B%AE/react.html"
  },
  {
    name: "v-1101c3d2",
    path: "/%E5%85%B3%E4%BA%8E%E6%88%91/family.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1101c3d2").then(next)
    },
  },
  {
    path: "/关于我/family.html",
    redirect: "/%E5%85%B3%E4%BA%8E%E6%88%91/family.html"
  },
  {
    path: "/关于我/family.html",
    redirect: "/%E5%85%B3%E4%BA%8E%E6%88%91/family.html"
  },
  {
    name: "v-6a44311d",
    path: "/%E9%A1%B9%E7%9B%AE/vue2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6a44311d").then(next)
    },
  },
  {
    path: "/项目/vue2.html",
    redirect: "/%E9%A1%B9%E7%9B%AE/vue2.html"
  },
  {
    path: "/项目/vue2.html",
    redirect: "/%E9%A1%B9%E7%9B%AE/vue2.html"
  },
  {
    name: "v-2c5e7486",
    path: "/%E9%A1%B9%E7%9B%AE/vue3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2c5e7486").then(next)
    },
  },
  {
    path: "/项目/vue3.html",
    redirect: "/%E9%A1%B9%E7%9B%AE/vue3.html"
  },
  {
    path: "/项目/vue3.html",
    redirect: "/%E9%A1%B9%E7%9B%AE/vue3.html"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]