/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "全栈攻城狮",
  "description": "全栈、前端、后端、工程师",
  "base": "/docs/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/docs/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "author",
        "content": "全栈攻城狮"
      }
    ],
    [
      "meta",
      {
        "name": "Keywords",
        "content": "个人博客，全栈攻城狮，前端，后端，javascript，java"
      }
    ]
  ],
  "pages": [
    {
      "title": "运动",
      "frontmatter": {
        "title": "运动"
      },
      "regularPath": "/%E5%85%B3%E4%BA%8E%E6%88%91/sports.html",
      "relativePath": "关于我/sports.md",
      "key": "v-54523be1",
      "path": "/%E5%85%B3%E4%BA%8E%E6%88%91/sports.html"
    },
    {
      "title": "玩耍",
      "frontmatter": {
        "title": "玩耍"
      },
      "regularPath": "/%E5%85%B3%E4%BA%8E%E6%88%91/play.html",
      "relativePath": "关于我/play.md",
      "key": "v-76f1a577",
      "path": "/%E5%85%B3%E4%BA%8E%E6%88%91/play.html"
    },
    {
      "title": "上班",
      "frontmatter": {
        "title": "上班"
      },
      "regularPath": "/%E5%85%B3%E4%BA%8E%E6%88%91/country.html",
      "relativePath": "关于我/country.md",
      "key": "v-0fc6feb2",
      "path": "/%E5%85%B3%E4%BA%8E%E6%88%91/country.html",
      "lastUpdated": "2022年5月9日星期一下午3点18分",
      "lastUpdatedTimestamp": 1652080712000,
      "createdTime": 1652080712000
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/dinner.jpg",
        "heroText": "诸葛四郎",
        "tagline": "不积跬步，无以至千里",
        "actionText": "关于我 →",
        "actionLink": "/关于我/country.md",
        "features": [
          {
            "title": "笔记",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "项目",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "面经",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2022-present 不明所以中心"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-004c6c70",
      "path": "/",
      "lastUpdated": "2022年5月9日星期一下午3点18分",
      "lastUpdatedTimestamp": 1652080712000,
      "createdTime": 1650438263000
    },
    {
      "title": "css",
      "frontmatter": {
        "title": "css"
      },
      "regularPath": "/%E9%9D%A2%E7%BB%8F/css.html",
      "relativePath": "面经/css.md",
      "key": "v-11cef15e",
      "path": "/%E9%9D%A2%E7%BB%8F/css.html",
      "headers": [
        {
          "level": 2,
          "title": "css-1",
          "slug": "css-1"
        }
      ],
      "lastUpdated": "2022年5月9日星期一下午3点18分",
      "lastUpdatedTimestamp": 1652080712000,
      "createdTime": 1652080712000
    },
    {
      "title": "html",
      "frontmatter": {
        "title": "html"
      },
      "regularPath": "/%E7%AC%94%E8%AE%B0/html.html",
      "relativePath": "笔记/html.md",
      "key": "v-3821ceb6",
      "path": "/%E7%AC%94%E8%AE%B0/html.html",
      "headers": [
        {
          "level": 2,
          "title": "html-1",
          "slug": "html-1"
        }
      ],
      "lastUpdated": "2022年5月9日星期一下午3点18分",
      "lastUpdatedTimestamp": 1652080712000,
      "createdTime": 1652080712000
    },
    {
      "title": "html",
      "frontmatter": {
        "title": "html"
      },
      "regularPath": "/%E9%9D%A2%E7%BB%8F/html.html",
      "relativePath": "面经/html.md",
      "key": "v-0e3002d9",
      "path": "/%E9%9D%A2%E7%BB%8F/html.html",
      "headers": [
        {
          "level": 2,
          "title": "目录",
          "slug": "目录"
        },
        {
          "level": 2,
          "title": "只用二级标题",
          "slug": "只用二级标题"
        },
        {
          "level": 2,
          "title": "图片",
          "slug": "图片"
        },
        {
          "level": 2,
          "title": "你好，one",
          "slug": "你好-one"
        },
        {
          "level": 3,
          "title": "表格",
          "slug": "表格"
        },
        {
          "level": 3,
          "title": "链接",
          "slug": "链接"
        },
        {
          "level": 3,
          "title": "Emoji",
          "slug": "emoji"
        },
        {
          "level": 3,
          "title": "自定义容器",
          "slug": "自定义容器"
        },
        {
          "level": 3,
          "title": "代码块中的行高亮",
          "slug": "代码块中的行高亮"
        }
      ],
      "lastUpdated": "2022年5月9日星期一下午3点18分",
      "lastUpdatedTimestamp": 1652080712000,
      "createdTime": 1652080712000
    },
    {
      "title": "css",
      "frontmatter": {
        "title": "css",
        "autoPrev": "html"
      },
      "regularPath": "/%E7%AC%94%E8%AE%B0/css.html",
      "relativePath": "笔记/css.md",
      "key": "v-7fd1ea16",
      "path": "/%E7%AC%94%E8%AE%B0/css.html",
      "headers": [
        {
          "level": 2,
          "title": "css-1",
          "slug": "css-1"
        }
      ],
      "lastUpdated": "2022年5月9日星期一下午3点18分",
      "lastUpdatedTimestamp": 1652080712000,
      "createdTime": 1652080712000
    },
    {
      "title": "java",
      "frontmatter": {
        "title": "java",
        "autoPrev": "react"
      },
      "regularPath": "/%E9%A1%B9%E7%9B%AE/java.html",
      "relativePath": "项目/java.md",
      "key": "v-4a71ca46",
      "path": "/%E9%A1%B9%E7%9B%AE/java.html",
      "headers": [
        {
          "level": 2,
          "title": "java-1",
          "slug": "java-1"
        }
      ],
      "lastUpdated": "2022年5月9日星期一下午3点18分",
      "lastUpdatedTimestamp": 1652080712000,
      "createdTime": 1652080712000
    },
    {
      "title": "react",
      "frontmatter": {
        "title": "react",
        "autoPrev": "vue2"
      },
      "regularPath": "/%E9%A1%B9%E7%9B%AE/react.html",
      "relativePath": "项目/react.md",
      "key": "v-24f06236",
      "path": "/%E9%A1%B9%E7%9B%AE/react.html",
      "headers": [
        {
          "level": 2,
          "title": "react-1",
          "slug": "react-1"
        }
      ],
      "lastUpdated": "2022年5月9日星期一下午3点18分",
      "lastUpdatedTimestamp": 1652080712000,
      "createdTime": 1652080712000
    },
    {
      "title": "摸鱼",
      "frontmatter": {
        "title": "摸鱼"
      },
      "regularPath": "/%E5%85%B3%E4%BA%8E%E6%88%91/family.html",
      "relativePath": "关于我/family.md",
      "key": "v-1101c3d2",
      "path": "/%E5%85%B3%E4%BA%8E%E6%88%91/family.html",
      "lastUpdated": "2022年5月9日星期一下午3点18分",
      "lastUpdatedTimestamp": 1652080712000,
      "createdTime": 1652080712000
    },
    {
      "title": "vue2",
      "frontmatter": {
        "title": "vue2"
      },
      "regularPath": "/%E9%A1%B9%E7%9B%AE/vue2.html",
      "relativePath": "项目/vue2.md",
      "key": "v-6a44311d",
      "path": "/%E9%A1%B9%E7%9B%AE/vue2.html",
      "headers": [
        {
          "level": 2,
          "title": "vue2-1",
          "slug": "vue2-1"
        },
        {
          "level": 2,
          "title": "vue2-2",
          "slug": "vue2-2"
        }
      ],
      "lastUpdated": "2022年5月9日星期一下午3点18分",
      "lastUpdatedTimestamp": 1652080712000,
      "createdTime": 1652080712000
    },
    {
      "title": "vue3",
      "frontmatter": {
        "title": "vue3"
      },
      "regularPath": "/%E9%A1%B9%E7%9B%AE/vue3.html",
      "relativePath": "项目/vue3.md",
      "key": "v-2c5e7486",
      "path": "/%E9%A1%B9%E7%9B%AE/vue3.html",
      "headers": [
        {
          "level": 2,
          "title": "vue3-1",
          "slug": "vue3-1"
        },
        {
          "level": 2,
          "title": "vue3-2",
          "slug": "vue3-2"
        }
      ]
    }
  ],
  "themeConfig": {
    "logo": "/assets/img/hero.png",
    "lastUpdated": "更新时间",
    "nav": [
      {
        "text": "关于我",
        "items": [
          {
            "text": "生活",
            "items": [
              {
                "text": "运动",
                "link": "/关于我/sports"
              },
              {
                "text": "玩耍",
                "link": "/关于我/play"
              }
            ]
          },
          {
            "text": "工作",
            "items": [
              {
                "text": "上班",
                "link": "/关于我/family"
              },
              {
                "text": "摸鱼",
                "link": "/关于我/country"
              }
            ]
          }
        ]
      },
      {
        "text": "笔记",
        "items": [
          {
            "text": "前端",
            "items": [
              {
                "text": "Html",
                "link": "/笔记/html"
              },
              {
                "text": "Css",
                "link": "/笔记/css"
              }
            ]
          }
        ]
      },
      {
        "text": "项目",
        "items": [
          {
            "text": "前端",
            "items": [
              {
                "text": "vue2",
                "link": "/项目/vue2"
              },
              {
                "text": "react",
                "link": "/项目/react"
              },
              {
                "text": "java",
                "link": "/项目/java"
              }
            ]
          }
        ]
      },
      {
        "text": "面经",
        "items": [
          {
            "text": "八股文",
            "items": [
              {
                "text": "html",
                "link": "/面经/html"
              },
              {
                "text": "css",
                "link": "/面经/css"
              }
            ]
          },
          {
            "text": "算法",
            "items": [
              {
                "text": "栈",
                "link": "/面经/html"
              },
              {
                "text": "队列",
                "link": "/面经/css"
              }
            ]
          }
        ]
      },
      {
        "text": "GitHub",
        "link": "https://github.com/klearing"
      }
    ]
  }
}