/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "羊加壶口",
  "description": "全栈、前端、后端、工程师",
  "base": "/docs/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/docs/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "author",
        "content": "全栈攻城狮"
      }
    ],
    [
      "meta",
      {
        "name": "Keywords",
        "content": "个人博客，全栈攻城狮，前端，后端，javascript，java"
      }
    ]
  ],
  "pages": [
    {
      "title": "react",
      "frontmatter": {
        "title": "react"
      },
      "regularPath": "/%E7%AC%94%E8%AE%B0/react.html",
      "relativePath": "笔记/react.md",
      "key": "v-683b7183",
      "path": "/%E7%AC%94%E8%AE%B0/react.html",
      "headers": [
        {
          "level": 2,
          "title": "目录",
          "slug": "目录"
        },
        {
          "level": 2,
          "title": "动态类和动态属性",
          "slug": "动态类和动态属性"
        }
      ]
    },
    {
      "title": "vue",
      "frontmatter": {
        "title": "vue"
      },
      "regularPath": "/%E7%AC%94%E8%AE%B0/vue.html",
      "relativePath": "笔记/vue.md",
      "key": "v-49fd8c75",
      "path": "/%E7%AC%94%E8%AE%B0/vue.html",
      "headers": [
        {
          "level": 2,
          "title": "目录",
          "slug": "目录"
        },
        {
          "level": 2,
          "title": "1. 动态类和动态属性",
          "slug": "_1-动态类和动态属性"
        },
        {
          "level": 3,
          "title": "动态类",
          "slug": "动态类"
        },
        {
          "level": 3,
          "title": "动态属性",
          "slug": "动态属性"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/dinner.jpg",
        "heroText": "羊加壶口",
        "tagline": "不积跬步，无以至千里",
        "actionText": "关于我 →",
        "actionLink": "/关于我/country.md",
        "features": [
          {
            "title": "王小波",
            "details": "一个人只拥有此生此世是不够的,他还应该拥有诗意的世界。"
          },
          {
            "title": "尼采",
            "details": "一个人知道自己为什么而活,就可以忍受任何一种生活"
          },
          {
            "title": "高级动物",
            "details": "矛盾 虚伪 贪婪 欺骗 幻想 疑惑 简单 善变 好强 无奈 孤独 脆弱 忍让 气愤 复杂 讨厌 嫉妒 阴险 争夺 埋怨 自私 无聊 变态 冒险"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2022-present 不明所以中心"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-674e7503",
      "path": "/",
      "lastUpdated": "2022年7月8日星期五上午9点35分",
      "lastUpdatedTimestamp": 1657244146000,
      "createdTime": 1650438263000
    },
    {
      "title": "上班",
      "frontmatter": {
        "title": "上班"
      },
      "regularPath": "/%E5%85%B3%E4%BA%8E%E6%88%91/country.html",
      "relativePath": "关于我/country.md",
      "key": "v-91614d68",
      "path": "/%E5%85%B3%E4%BA%8E%E6%88%91/country.html",
      "lastUpdated": "2022年5月9日星期一下午3点18分",
      "lastUpdatedTimestamp": 1652080712000,
      "createdTime": 1652080712000
    },
    {
      "title": "摸鱼",
      "frontmatter": {
        "title": "摸鱼"
      },
      "regularPath": "/%E5%85%B3%E4%BA%8E%E6%88%91/family.html",
      "relativePath": "关于我/family.md",
      "key": "v-732c4808",
      "path": "/%E5%85%B3%E4%BA%8E%E6%88%91/family.html",
      "lastUpdated": "2022年5月9日星期一下午3点18分",
      "lastUpdatedTimestamp": 1652080712000,
      "createdTime": 1652080712000
    },
    {
      "title": "玩耍",
      "frontmatter": {
        "title": "玩耍"
      },
      "regularPath": "/%E5%85%B3%E4%BA%8E%E6%88%91/play.html",
      "relativePath": "关于我/play.md",
      "key": "v-68c91ddc",
      "path": "/%E5%85%B3%E4%BA%8E%E6%88%91/play.html",
      "lastUpdated": "2022年7月8日星期五上午9点35分",
      "lastUpdatedTimestamp": 1657244146000,
      "createdTime": 1657244146000
    },
    {
      "title": "运动",
      "frontmatter": {
        "title": "运动"
      },
      "regularPath": "/%E5%85%B3%E4%BA%8E%E6%88%91/sports.html",
      "relativePath": "关于我/sports.md",
      "key": "v-233cf9c6",
      "path": "/%E5%85%B3%E4%BA%8E%E6%88%91/sports.html",
      "lastUpdated": "2022年7月8日星期五上午9点35分",
      "lastUpdatedTimestamp": 1657244146000,
      "createdTime": 1657244146000
    },
    {
      "title": "css",
      "frontmatter": {
        "title": "css",
        "autoPrev": "html"
      },
      "regularPath": "/%E7%AC%94%E8%AE%B0/css.html",
      "relativePath": "笔记/css.md",
      "key": "v-2ff711fb",
      "path": "/%E7%AC%94%E8%AE%B0/css.html",
      "headers": [
        {
          "level": 2,
          "title": "目录",
          "slug": "目录"
        },
        {
          "level": 2,
          "title": "1.各种height等值的含义",
          "slug": "_1-各种height等值的含义"
        },
        {
          "level": 3,
          "title": "1.offsetWidth",
          "slug": "_1-offsetwidth"
        },
        {
          "level": 3,
          "title": "2.offsetLeft",
          "slug": "_2-offsetleft"
        },
        {
          "level": 3,
          "title": "3.scrollWidth",
          "slug": "_3-scrollwidth"
        },
        {
          "level": 3,
          "title": "4.scrollTop",
          "slug": "_4-scrolltop"
        },
        {
          "level": 3,
          "title": "5.clientWidth",
          "slug": "_5-clientwidth"
        },
        {
          "level": 3,
          "title": "6.clientLeft",
          "slug": "_6-clientleft"
        },
        {
          "level": 3,
          "title": "7.mousemove事件相关",
          "slug": "_7-mousemove事件相关"
        },
        {
          "level": 2,
          "title": "2.结构伪类选择器",
          "slug": "_2-结构伪类选择器"
        }
      ],
      "lastUpdated": "2022年7月8日星期五上午10点44分",
      "lastUpdatedTimestamp": 1657248269000,
      "createdTime": 1652080712000
    },
    {
      "title": "html",
      "frontmatter": {
        "title": "html"
      },
      "regularPath": "/%E7%AC%94%E8%AE%B0/html.html",
      "relativePath": "笔记/html.md",
      "key": "v-739c915b",
      "path": "/%E7%AC%94%E8%AE%B0/html.html",
      "headers": [
        {
          "level": 2,
          "title": "目录",
          "slug": "目录"
        },
        {
          "level": 2,
          "title": "1.html、body、document和window",
          "slug": "_1-html、body、document和window"
        },
        {
          "level": 3,
          "title": "",
          "slug": "_1-html"
        },
        {
          "level": 3,
          "title": "",
          "slug": "_2-body"
        },
        {
          "level": 3,
          "title": "",
          "slug": "_3-document"
        },
        {
          "level": 3,
          "title": "",
          "slug": "_4-window"
        },
        {
          "level": 2,
          "title": "2.",
          "slug": "_2"
        }
      ],
      "lastUpdated": "2022年5月9日星期一下午3点18分",
      "lastUpdatedTimestamp": 1652080712000,
      "createdTime": 1652080712000
    },
    {
      "title": "css",
      "frontmatter": {
        "title": "css"
      },
      "regularPath": "/%E9%9D%A2%E7%BB%8F/css.html",
      "relativePath": "面经/css.md",
      "key": "v-b184a194",
      "path": "/%E9%9D%A2%E7%BB%8F/css.html",
      "headers": [
        {
          "level": 2,
          "title": "css-1",
          "slug": "css-1"
        }
      ],
      "lastUpdated": "2022年5月9日星期一下午3点18分",
      "lastUpdatedTimestamp": 1652080712000,
      "createdTime": 1652080712000
    },
    {
      "title": "java",
      "frontmatter": {
        "title": "java",
        "autoPrev": "react"
      },
      "regularPath": "/%E9%A1%B9%E7%9B%AE/java.html",
      "relativePath": "项目/java.md",
      "key": "v-1641dd82",
      "path": "/%E9%A1%B9%E7%9B%AE/java.html",
      "headers": [
        {
          "level": 2,
          "title": "java-1",
          "slug": "java-1"
        }
      ],
      "lastUpdated": "2022年5月9日星期一下午3点18分",
      "lastUpdatedTimestamp": 1652080712000,
      "createdTime": 1652080712000
    },
    {
      "title": "html",
      "frontmatter": {
        "title": "html"
      },
      "regularPath": "/%E9%9D%A2%E7%BB%8F/html.html",
      "relativePath": "面经/html.md",
      "key": "v-49aac57e",
      "path": "/%E9%9D%A2%E7%BB%8F/html.html",
      "headers": [
        {
          "level": 2,
          "title": "目录",
          "slug": "目录"
        },
        {
          "level": 2,
          "title": "只用二级标题",
          "slug": "只用二级标题"
        },
        {
          "level": 2,
          "title": "图片",
          "slug": "图片"
        },
        {
          "level": 2,
          "title": "你好，one",
          "slug": "你好-one"
        },
        {
          "level": 3,
          "title": "表格",
          "slug": "表格"
        },
        {
          "level": 3,
          "title": "链接",
          "slug": "链接"
        },
        {
          "level": 3,
          "title": "Emoji",
          "slug": "emoji"
        },
        {
          "level": 3,
          "title": "自定义容器",
          "slug": "自定义容器"
        },
        {
          "level": 3,
          "title": "代码块中的行高亮",
          "slug": "代码块中的行高亮"
        }
      ],
      "lastUpdated": "2022年5月9日星期一下午3点18分",
      "lastUpdatedTimestamp": 1652080712000,
      "createdTime": 1652080712000
    },
    {
      "title": "vue2",
      "frontmatter": {
        "title": "vue2"
      },
      "regularPath": "/%E9%A1%B9%E7%9B%AE/vue2.html",
      "relativePath": "项目/vue2.md",
      "key": "v-b482187c",
      "path": "/%E9%A1%B9%E7%9B%AE/vue2.html",
      "headers": [
        {
          "level": 2,
          "title": "vue2-1",
          "slug": "vue2-1"
        },
        {
          "level": 2,
          "title": "vue2-2",
          "slug": "vue2-2"
        }
      ],
      "lastUpdated": "2022年7月8日星期五上午9点35分",
      "lastUpdatedTimestamp": 1657244146000,
      "createdTime": 1652080712000
    },
    {
      "title": "react",
      "frontmatter": {
        "title": "react",
        "autoPrev": "vue2"
      },
      "regularPath": "/%E9%A1%B9%E7%9B%AE/react.html",
      "relativePath": "项目/react.md",
      "key": "v-355c7c4a",
      "path": "/%E9%A1%B9%E7%9B%AE/react.html",
      "headers": [
        {
          "level": 2,
          "title": "react-1",
          "slug": "react-1"
        }
      ],
      "lastUpdated": "2022年5月9日星期一下午3点18分",
      "lastUpdatedTimestamp": 1652080712000,
      "createdTime": 1652080712000
    },
    {
      "title": "vue3",
      "frontmatter": {
        "title": "vue3"
      },
      "regularPath": "/%E9%A1%B9%E7%9B%AE/vue3.html",
      "relativePath": "项目/vue3.md",
      "key": "v-254b8862",
      "path": "/%E9%A1%B9%E7%9B%AE/vue3.html",
      "headers": [
        {
          "level": 2,
          "title": "vue3-1",
          "slug": "vue3-1"
        },
        {
          "level": 2,
          "title": "vue3-2",
          "slug": "vue3-2"
        }
      ],
      "lastUpdated": "2022年7月8日星期五上午9点35分",
      "lastUpdatedTimestamp": 1657244146000,
      "createdTime": 1657244146000
    }
  ],
  "themeConfig": {
    "logo": "/assets/img/hero.png",
    "lastUpdated": "更新时间",
    "nav": [
      {
        "text": "关于我",
        "items": [
          {
            "text": "生活",
            "items": [
              {
                "text": "运动",
                "link": "/关于我/sports"
              },
              {
                "text": "玩耍",
                "link": "/关于我/play"
              }
            ]
          },
          {
            "text": "工作",
            "items": [
              {
                "text": "上班",
                "link": "/关于我/family"
              },
              {
                "text": "摸鱼",
                "link": "/关于我/country"
              }
            ]
          }
        ]
      },
      {
        "text": "笔记",
        "items": [
          {
            "text": "前端",
            "items": [
              {
                "text": "Html",
                "link": "/笔记/html"
              },
              {
                "text": "Css",
                "link": "/笔记/css"
              }
            ]
          }
        ]
      },
      {
        "text": "项目",
        "items": [
          {
            "text": "前端",
            "items": [
              {
                "text": "vue2",
                "link": "/项目/vue2"
              },
              {
                "text": "react",
                "link": "/项目/react"
              },
              {
                "text": "java",
                "link": "/项目/java"
              }
            ]
          }
        ]
      },
      {
        "text": "面经",
        "items": [
          {
            "text": "八股文",
            "items": [
              {
                "text": "html",
                "link": "/面经/html"
              },
              {
                "text": "css",
                "link": "/面经/css"
              }
            ]
          },
          {
            "text": "算法",
            "items": [
              {
                "text": "栈",
                "link": "/面经/html"
              },
              {
                "text": "队列",
                "link": "/面经/css"
              }
            ]
          }
        ]
      },
      {
        "text": "GitHub",
        "link": "https://github.com/klearing"
      }
    ]
  }
}